import img1 from '../../asset/speaker.jpg'


export const ProductData = [
    {
        id: 1,
        product: "XIAOMI Redmi A3 6.71 3GB RAM/64GB ROM Android 12 - Blue + FREE GIFT",
        price: 95750,
        description: "Redmi A3 is the Smooth & Stylish phone that will always make heads turn with its luxurious Premium Halo Design. ",
        brand: 'Xiaomi',
        phone: '08958885858',
        email: 'dave@gmail.com',
        image: <img src={img1} style={{height:260}} alt="Sunset in the mountains"className='w-full'/>,
        category: 'Phone',
    },
    {
        id: 2,
        product: "Apple IPhone 15 Pro Max 512gb - Nano Sim - Natural Titanium",
        price: 2250000,
        description: "The iPhone 15 Pro Max uses Titanium for its frame, which is lighter and stronger than before.",
        brand: 'Apple',
        phone: '08958885858',
        email: 'dave@gmail.com',
        image: <img src={img1} style={{height:260}} alt="Sunset in the mountains"className='w-full'/>,
        category: 'Phone',
    },
    {
        id: 3,
        product: "Hp EliteBook 840 G6 Touchscreen Intel Core I5 16GB RAM/512GB SSD/Backlit Keyboard/FP Win 11 Pro",
        price: 495000,
        description: "HP ELITEBOOK 840 G6 - INTEL CORE I5 - FINGERPRINT READER- BACKLIT KEYBOARD- FULL HD DISPLAY",
        brand: 'Hewlett-Packard',
        phone: '08958885858',
        email: 'dave@gmail.com',
        image: <img src={img1} style={{height:260}} alt="Sunset in the mountains"className='w-full'/>,
        category: 'Computer',

    },
    {
        id: 4,
        product: "DELL OptiPlex 9030 COREi5 , 8GB RAM, 1TB HDD, Win 10 Pro & MS Office 2016",
        price: 480000,
        description: "Robust performance: The OptiPlex 9030 All-in-One provides performance features to power your organization’s productivity.",
        brand: 'Dell',
        phone: '08958885858',
        email: 'dave@gmail.com',
        image: <img src={img1} style={{height:260}} alt="Sunset in the mountains"className='w-full'/>,
        category: 'Computer',

    },
    {
        id: 5,
        product: "Realme Wireless Wireless Earbuds Bluetooth F9 Max Headphones Earpöds Earpiece Fingerprint Touch Control Bass Iphone Headset",
        price: 7759,
        description: "Portable and light weight with on-the-go charging caseGreat for use at work or home or on-the-goRechargeable storage case",
        brand: 'Samsung',
        phone: '08958885858',
        email: 'dave@gmail.com',
        image: <img src={img1} style={{height:260}} alt="Sunset in the mountains"className='w-full'/>,
        category: 'Headphones',

    },
    {
        id: 6,
        product: "P47 IMPROVED 5.0 Wireless Bluetooth Stereo Foldable Headse",
        price: 5087,
        description: "Portable and light weight with on-the-go charging caseGreat for use at work or home or on-the-goRechargeable storage case",
        brand: 'Oraimo',
        phone: '08958885858',
        email: 'dave@gmail.com',
        image: <img src={img1} style={{height:260}} alt="Sunset in the mountains"className='w-full'/>,
        category: 'Headphones',

    },
    {
        id: 7,
        product: "T900 Ultra2 Smart Watch 2.19-inch High Bluetooth Call Intelligent IP67 Waterproof",
        price: 11999,
        description: "The Bluetooth call function requires dual Bluetooth signal support, so you need to connect twice according to the instructions",
        brand: 'itel',
        phone: '08958885858',
        email: 'dave@gmail.com',
        image: <img src={img1} style={{height:260}} alt="Sunset in the mountains"className='w-full'/>,
        category: 'Smart Watch',

    },
    {
        id: 8,
        product: "T800 Smart Watch Ultra 8 Door Access Smartwatch Series 8",
        price: 10999,
        description: "High-definition bluetooth fairy tale, off-screen pointer, cover hand off screen, custom picture, APP background download picture, QR",
        brand: 'Apple',
        phone: '08958885858',
        email: 'dave@gmail.com',
        image: <img src={img1} style={{height:260}} alt="Sunset in the mountains"className='w-full'/>,
        category: 'Smart Watch',

    },
    {
        id: 9,
        product: "Andoer TFT Portable Digital Camera 48MP 4K Ultra HD 16X Zoom - 3in",
        price: 69990,
        description: "Ensure your photos are always sharp and perfectly focused with the multipoint autofocus system of this",
        brand: 'Sony',
        phone: '08958885858',
        email: 'dave@gmail.com',
        image: <img src={img1} style={{height:260}} alt="Sunset in the mountains"className='w-full'/>,
        category: 'Camera',

    },
    {
        id: 10,
        product: "Mini Photo Picture Video Pocket Camera -Oyibo Used- Rough And No Packet",
        price: 29999,
        description: "Do you need a smart mini camera for your video and photos shoot. Then rush and get this affordable mini camera. It shoots your videos",
        brand: 'Lumix',
        phone: '08958885858',
        email: 'dave@gmail.com',
        image: <img src={img1} style={{height:260}} alt="Sunset in the mountains"className='w-full'/>,
        category: 'Smart Watch',

    },
    {
        id: 11,
        product: "Waterproof Anti-S Rat H Game Prote Tive Outer Asing For PS5 Game Onsole-black-39*26*9CM",
        price: 24622,
        description: "Features: 1. High qu ty: Made of high qu ty material, it is soft, dustproof, waterproof, washable and durable. 2. Pra ti al: Inside smooth to",
        brand: 'Sony',
        phone: '08958885858',
        email: 'dave@gmail.com',
        image: <img src={img1} style={{height:260}} alt="Sunset in the mountains"className='w-full'/>,
        category: 'Gaming',

    },
    {
        id: 12,
        product: "Powkiddy Consoles Portable Handheld Game 4.0-inch IPS",
        price: 154200,
        description: "High-performance processor: ARM quad-core 1.8GHz processor, capable of running FPS games smoothly at a speed of 60 Hz, bringing",
        brand: 'Microsoft',
        phone: '08958885858',
        email: 'dave@gmail.com',
        image: <img src={img1} style={{height:260}} alt="Sunset in the mountains"className='w-full'/>,
        category: 'Gaming',

    },
]